name: hls4ml_explorer
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.19
  - pandas
  - numpy
  - scikit-learn
  - tensorflow
  - graphviz
  - matplotlib
  - pyyaml
  - json5
  - multiprocess
  - pip
  - pip:
      - hls4ml
      - gurobipy
